name: Deploy Ello API to AWS AppRunner Production Environment

# run on PR merged into main branch
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/ecr_ellotest_repo:latest .
          docker push $ECR_REGISTRY/ecr_ellotest_repo:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          tf_version: 1.0.9

      - name: Initialize Terraform
        run: cd deployment && terraform init

      - name: Plan Changes
        run: cd deployment && terraform plan -out=tfplan

      - name: Apply Changes
        run: cd deployment && terraform apply -auto-approve tfplan

      - name: Clean Up
        run: cd deployment && rm tfplan 