name: Staging tests

# run on PR merged into develop branch
on:
  push:
    branches: [develop]

jobs:
  run-lints-and-unit-tests-staging:
    name: "Run Lints and Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Run Unit Tests
        run: |
          npm run test
